# Generated by Django 4.1.6 on 2023-02-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='moderation',
            field=models.BooleanField(default=False),
        ),
    ]
