# Generated by Django 4.1.7 on 2023-03-16 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_segments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
