# Generated by Django 4.1.7 on 2023-02-25 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_divination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.SlugField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='quote',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes_divination.category'),
        ),
    ]
