# Generated by Django 4.1.7 on 2023-03-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_divination', '0003_alter_category_options_alter_quote_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_alt',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
