# Generated by Django 4.1.6 on 2023-02-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TarotSuits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suits_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_1', models.ImageField(blank=True, upload_to='suits_images')),
                ('image_2', models.ImageField(blank=True, upload_to='suits_images')),
                ('image_3', models.ImageField(blank=True, upload_to='suits_images')),
                ('url', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Масть таро',
                'verbose_name_plural': 'Масти таро',
            },
        ),
    ]
