# Generated by Django 4.1.6 on 2023-02-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot_cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarotsuits',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='tarot_cards/suits_images'),
        ),
        migrations.AlterField(
            model_name='tarotsuits',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='tarot_cards/suits_images'),
        ),
        migrations.AlterField(
            model_name='tarotsuits',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='tarot_cards/suits_images'),
        ),
    ]
