# Generated by Django 4.1.6 on 2023-02-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot_cards', '0002_alter_tarotsuits_image_1_alter_tarotsuits_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarotsuits',
            name='image_4',
            field=models.ImageField(blank=True, upload_to='tarot_cards/suits_images'),
        ),
    ]
