# Generated by Django 4.1.6 on 2023-02-16 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot_cards', '0003_tarotsuits_image_4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image_1', models.ImageField(blank=True, upload_to='tarot_cards/cards_images')),
                ('general_up_tags', models.TextField(blank=True, null=True)),
                ('general_down_tags', models.TextField(blank=True, null=True)),
                ('general_meaning', models.TextField(blank=True, null=True)),
                ('general_up', models.TextField(blank=True, null=True)),
                ('general_down', models.TextField(blank=True, null=True)),
                ('love_up_tags', models.TextField(blank=True, null=True)),
                ('love_down_tags', models.TextField(blank=True, null=True)),
                ('love_up', models.TextField(blank=True, null=True)),
                ('love_down', models.TextField(blank=True, null=True)),
                ('сareer_up_tags', models.TextField(blank=True, null=True)),
                ('сareer_down_tags', models.TextField(blank=True, null=True)),
                ('сareer_up', models.TextField(blank=True, null=True)),
                ('сareer_down', models.TextField(blank=True, null=True)),
                ('finance_up_tags', models.TextField(blank=True, null=True)),
                ('finance_down_tags', models.TextField(blank=True, null=True)),
                ('finance_up', models.TextField(blank=True, null=True)),
                ('finance_down', models.TextField(blank=True, null=True)),
                ('past_meaning', models.TextField(blank=True, null=True)),
                ('present_meaning', models.TextField(blank=True, null=True)),
                ('future_meaning', models.TextField(blank=True, null=True)),
                ('card_of_day', models.TextField(blank=True, null=True)),
                ('card_advice', models.TextField(blank=True, null=True)),
                ('yes_no', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.SlugField(max_length=100, unique=True)),
                ('card_suit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarot_cards.tarotsuits')),
            ],
            options={
                'verbose_name': 'Карта',
                'verbose_name_plural': 'Карты',
            },
        ),
    ]
