# Generated by Django 4.1.6 on 2023-02-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot_cards', '0004_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarotsuits',
            name='seo_tags',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
