# Generated by Django 4.1.6 on 2023-02-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot_cards', '0005_tarotsuits_seo_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarotsuits',
            name='negative_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarotsuits',
            name='positive_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
