# Generated by Django 4.1.6 on 2023-02-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot_cards', '0006_tarotsuits_negative_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarotsuits',
            name='alternative_names',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tarotsuits',
            name='astrological_signs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tarotsuits',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tarotsuits',
            name='seo_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='yes_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tarotsuits',
            name='seo_tags',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
