# Generated by Django 4.1.6 on 2023-02-17 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarot_cards', '0008_card_seo_description_card_seo_key_words'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='сareer_down',
            new_name='career_down',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='сareer_down_tags',
            new_name='career_down_tags',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='сareer_up',
            new_name='career_up',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='сareer_up_tags',
            new_name='career_up_tags',
        ),
    ]
