# Generated by Django 4.1.7 on 2023-02-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot_cards', '0009_rename_сareer_down_card_career_down_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarotsuits',
            name='image_4',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='tarot_cards/suits_images'),
        ),
    ]
