# Generated by Django 4.1.7 on 2023-03-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_characteristic', '0003_weekdaycharacter_color_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorcharacter',
            name='color_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='weekdaycharacter',
            name='color_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
