# Generated by Django 4.1.7 on 2023-03-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_characteristic', '0004_alter_colorcharacter_color_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthDayCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color_code', models.CharField(max_length=20, null=True)),
                ('text', models.TextField()),
                ('url', models.SlugField(max_length=100, unique=True)),
                ('seo_description', models.TextField(blank=True, null=True)),
                ('seo_keywords', models.CharField(blank=True, max_length=300, null=True)),
                ('moderation', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'День месяца',
                'verbose_name_plural': 'Дни месяца',
            },
        ),
    ]
